version: "3.9" # optional since v1.27.0
services:
    auth:
        build: .
        ports:
            - 5051:5051
            - 8081:8081
        env_file:
            - ./dev.env
        environment:
            - BEEMAUTH_PORT=5051
            - BEEMAUTH_DBHOST=database
            - BEEMAUTH_DBPORT=5432
            - BEEMAUTH_DBUSER=postgres
            - BEEMAUTH_DBPASSWORD=postgres
            - BEEMAUTH_DBNAME=beem_auth
        depends_on:
            database:
                condition: service_healthy
        networks:
            - beem-net

    database:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=beem_auth
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - beem-net

    hydra:
        image: oryd/hydra:v1.9.2
        ports:
            - "4444:4444" # Public port
            - "4445:4445" # Admin port
            - "5555:5555" # Port for hydra token user
        command:
            serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
        volumes:
            -
                type: bind
                source: ./hydra-config
                target: /etc/config/hydra
        environment:
            - DSN=postgres://postgres:postgres@database:5432/hydra?sslmode=disable
            - SECRETS_SYSTEM=VERY_SecRet_beEm_!@
        restart: unless-stopped
        depends_on:
            - hydra-migrate
        networks:
            - beem-net

    hydra-migrate:
        image: oryd/hydra:v1.9.2
        environment:
            - DSN=postgres://postgres:postgres@database:5432/hydra?sslmode=disable
        command:
            migrate sql --yes -e
        restart: on-failure
        depends_on:
            database:
                condition: service_healthy
        networks:
            - beem-net

networks:
    beem-net: