version: "3.9" # optional since v1.27.0
services:
    auth:
        build: .
        ports:
            - 5051:5051
            - 8081:8081
        env_file:
            - ./dev.env
        environment:
            - BEEMAUTH_PORT=5051
            - BEEMAUTH_DBHOST=database
            - BEEMAUTH_DBPORT=5432
            - BEEMAUTH_DBUSER=postgres
            - BEEMAUTH_DBPASSWORD=postgres
            - BEEMAUTH_DBNAME=beem_auth
        depends_on:
            database:
                condition: service_healthy
        networks:
            - intranet

    database:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=beem_auth
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - intranet

    hydra:
        image: oryd/hydra:v1.9.2-sqlite
        ports:
            - "4444:4444" # Public port
            - "4445:4445" # Admin port
            - "5555:5555" # Port for hydra token user
        command:
            serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
        volumes:
            -
                type: volume
                source: hydra-sqlite
                target: /var/lib/sqlite
                read_only: false
            -
                type: bind
                source: ./contrib/quickstart/5-min
                target: /etc/config/hydra
        environment:
            - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
        restart: unless-stopped
        depends_on:
            - hydra-migrate
        networks:
            - intranet

    hydra-migrate:
        image: oryd/hydra:v1.9.2-sqlite
        environment:
            - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
        command:
            migrate -c /etc/config/hydra/hydra.yml sql -e --yes
        volumes:
            -
                type: volume
                source: hydra-sqlite
                target: /var/lib/sqlite
                read_only: false
            -
                type: bind
                source: ./contrib/quickstart/5-min
                target: /etc/config/hydra
        restart: on-failure
        networks:
            - intranet

    consent:
        environment:
            - HYDRA_ADMIN_URL=http://hydra:4445
        image: oryd/hydra-login-consent-node:v1.9.2
        ports:
            - "3000:3000"
        restart: unless-stopped
        networks:
            - intranet

networks:
    intranet:

volumes:
    hydra-sqlite: