name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Install dependencies
        run: make dependencies

      - name: Check GRPC files
        run: |
          make generate
          git diff --exit-code internal/pb

      - name: Test
        run: make test
